### ISSUE TITLE
Duplicated drives

### ISSUE THREAD

**Issue by OlaPAH** [CodeForPoznan/pah-fm#284] opened 2019-07-24 08:02 UTC
New issue with the tool reported this morning: as you may see on a screenshot provided by the driver, one ride he submitted got duplicated, as he says, 8 times. I’ll now delete 7 copies of it, but it’s just weird how this even happened. He couldn’t have possibly submitted it accidentally 8 times in a row..
Another glitch, apparently.

**Comment by OlaPAH** [comment] 2019-07-24 08:04
![screen](https://user-images.githubusercontent.com/43967668/61776000-5b7f2800-adfa-11e9-8320-d7c1ccebf63e.jpg)

**Comment by magul** [comment] 2019-07-31 15:33
Closing that one as duplicate of #278

**Closed** 2019-07-31 15:41 UTC
