### ISSUE TITLE
i18n: Translate app

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/pah-fm#63] opened 2018-11-20 21:14 UTC
Add translations for all languages.

Begin with full Polish translation.

**Comment by magul** [comment] 2019-01-27 19:46
Ok, @jacol12345 I found #58, so I believe that this task has to track translation progress for targeted languages. I will make sub-issues created for these languages.

**Comment by adamgajzlerowicz** [comment] 2019-02-04 16:18
duplicate of https://github.com/CodeForPoznan/pah-fm/issues/157

**Closed by adamgajzlerowicz** 2019-02-04 16:18 UTC
Labels: Epic, frontend, pah input
