### ISSUE TITLE
Translation issue in navigation component

### ISSUE THREAD

**Issue by juliaanholcer** [CodeForPoznan/pah-fm#188] opened 2019-03-07 21:23 UTC
Navigation's link [Drives, Add new drives] in the side navigation isn't translated when the language is changed.

**Comment by monikakrawczak** [comment] 2019-03-11 15:01
Tested and works properly now - cannot reproduce this issue. @adamgajzlerowicz could you confirm is it still occur?

**Comment by adamgajzlerowicz** [comment] 2019-03-11 21:06
Fixed and merged :)

**Closed by adamgajzlerowicz** 2019-03-11 21:06 UTC
Labels: bug
